# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SLCarouselViewExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SLCarouselView
  pod 'PureLayout'
  pod 'SDWebImage'
  pod 'SLCarouselView', :git => 'https://github.com/liusally/SLCarouselView.git'

end
